from __future__ import annotations

QUESTIONS_A = [{'id': 'ch00-q01',
  'chapterId': 'ch00',
  'question': 'f(x)=2x（0<x<1）在支撐集上的總積分是多少？',
  'answer': '1。',
  'explanation': '∫₀¹2x dx=[x²]₀¹=1，因此可作為該支撐上的密度。'},
 {'id': 'ch00-q02',
  'chapterId': 'ch00',
  'question': '同一密度下 P(X≤1/2) 是多少？',
  'answer': '1/4。',
  'explanation': '∫₀^{1/2}2x dx=(1/2)²=1/4。'},
 {'id': 'ch00-q03',
  'chapterId': 'ch00',
  'question': '只由樣本 X₁,…,X_n 構成、且不含未知參數的函數稱為什麼？',
  'answer': '統計量。',
  'explanation': '統計量只能依賴觀察樣本與已知常數，不能含未知母體參數。'},
 {'id': 'ch00-q04',
  'chapterId': 'ch00',
  'question': '一階 Taylor 近似 g(x)≈g(a)+g′(a)(x-a) 在高等統計中常用來支援哪個大樣本方法？',
  'answer': 'Delta method。',
  'explanation': 'Delta method 把統計量的漸近常態性透過可微函數傳遞。'},
 {'id': 'ch00-q05',
  'chapterId': 'ch00',
  'question': '若某『統計量』公式仍含未知 μ，是否可直接稱為統計量？',
  'answer': '不可以。',
  'explanation': '未知參數 μ 尚未被樣本取代時，該式不符合統計量不含未知參數的定義。'},
 {'id': 'ch01-q01',
  'chapterId': 'ch01',
  'question': 'P(A)=0.6、P(B)=0.5、P(A∩B)=0.3，P(A∪B) 為多少？',
  'answer': '0.8。',
  'explanation': '0.6+0.5-0.3=0.8。'},
 {'id': 'ch01-q02',
  'chapterId': 'ch01',
  'question': '同一組數值下，A 與 B 是否獨立？',
  'answer': '是。',
  'explanation': 'P(A)P(B)=0.6×0.5=0.3=P(A∩B)。'},
 {'id': 'ch01-q03',
  'chapterId': 'ch01',
  'question': '同一組數值下 P(A|B) 是多少？',
  'answer': '0.6。',
  'explanation': 'P(A|B)=0.3/0.5=0.6，等於 P(A)，也呼應獨立性。'},
 {'id': 'ch01-q04',
  'chapterId': 'ch01',
  'question': '先驗 P(A)=0.1，P(B|A)=0.9，P(B|Aᶜ)=0.2，P(A|B) 是多少？',
  'answer': '1/3。',
  'explanation': 'P(B)=0.09+0.18=0.27，所以 P(A|B)=0.09/0.27=1/3。'},
 {'id': 'ch01-q05',
  'chapterId': 'ch01',
  'question': '互斥且機率都大於 0 的兩事件是否可能獨立？',
  'answer': '不可能。',
  'explanation': '互斥使 P(A∩B)=0，但獨立會要求 P(A)P(B)>0，兩者矛盾。'},
 {'id': 'ch02-q01',
  'chapterId': 'ch02',
  'question': 'X~Uniform(0,2) 時 F(1.5) 是多少？',
  'answer': '0.75。',
  'explanation': '0<x<2 時 F(x)=x/2，所以 F(1.5)=0.75。'},
 {'id': 'ch02-q02',
  'chapterId': 'ch02',
  'question': '同一分配下 P(0.5<X≤1.5) 是多少？',
  'answer': '0.5。',
  'explanation': 'F(1.5)-F(0.5)=0.75-0.25=0.5。'},
 {'id': 'ch02-q03',
  'chapterId': 'ch02',
  'question': '連續型隨機變數一般有 P(X=x₀)=多少？',
  'answer': '0。',
  'explanation': '單點集合的積分面積為 0；這不代表 f(x₀)=0。'},
 {'id': 'ch02-q04',
  'chapterId': 'ch02',
  'question': 'CDF 必須具備哪個方向的單調性？',
  'answer': '非遞減。',
  'explanation': '若 x 增大，事件 {X≤x} 只會擴大，因此 F 不會下降。'},
 {'id': 'ch02-q05',
  'chapterId': 'ch02',
  'question': 'PDF 的數值 f(x₀) 能否直接解讀成 P(X=x₀)？',
  'answer': '不能。',
  'explanation': '連續分配的機率是密度在區間上的積分，不是單點密度高度。'},
 {'id': 'ch03-q01',
  'chapterId': 'ch03',
  'question': 'X~Binomial(5,0.2)，P(X=1) 是多少？',
  'answer': '0.4096。',
  'explanation': '5×0.2×0.8⁴=0.4096。'},
 {'id': 'ch03-q02',
  'chapterId': 'ch03',
  'question': 'X~Poisson(2)，P(X=0) 約多少？',
  'answer': '約 0.1353。',
  'explanation': 'P(0)=e^{-2}≈0.135335。'},
 {'id': 'ch03-q03',
  'chapterId': 'ch03',
  'question': 'Geometric(p=0.25) 若 X 表示直到第一次成功的試驗次數，E(X) 是多少？',
  'answer': '4。',
  'explanation': '在支撐 1,2,… 的參數化下 E(X)=1/p=4。'},
 {'id': 'ch03-q04',
  'chapterId': 'ch03',
  'question': '二項分配的 n 次試驗除了成功率固定外，還需要什麼重要條件？',
  'answer': '試驗彼此獨立。',
  'explanation': '固定 n、每次兩種結果、成功率 p 固定且獨立是標準 Binomial 模型條件。'},
 {'id': 'ch03-q05',
  'chapterId': 'ch03',
  'question': 'Poisson(λ) 的平均數與變異數各是多少？',
  'answer': '兩者都是 λ。',
  'explanation': 'Poisson 分配具有 E(X)=Var(X)=λ。'},
 {'id': 'ch04-q01',
  'chapterId': 'ch04',
  'question': 'X~Exponential(rate=0.5)，P(X>2) 約多少？',
  'answer': '約 0.3679。',
  'explanation': '存活函數 e^{-λx}=e^{-1}≈0.3679。'},
 {'id': 'ch04-q02',
  'chapterId': 'ch04',
  'question': 'Y~Gamma(α=3, rate=2)，E(Y) 是多少？',
  'answer': '1.5。',
  'explanation': '本書用 rate 參數化，E(Y)=α/λ=3/2=1.5。'},
 {'id': 'ch04-q03',
  'chapterId': 'ch04',
  'question': '同一 Gamma 分配的 Var(Y) 是多少？',
  'answer': '0.75。',
  'explanation': 'Var(Y)=α/λ²=3/4=0.75。'},
 {'id': 'ch04-q04',
  'chapterId': 'ch04',
  'question': 'U~Beta(2,3)，E(U) 是多少？',
  'answer': '0.4。',
  'explanation': 'Beta(α,β) 的平均數 α/(α+β)=2/5=0.4。'},
 {'id': 'ch04-q05',
  'chapterId': 'ch04',
  'question': '若 X~N(μ,σ²)，標準化 Z 應除以 σ 還是 σ²？',
  'answer': '除以 σ。',
  'explanation': 'Z=(X-μ)/σ；σ 是標準差。'},
 {'id': 'ch05-q01',
  'chapterId': 'ch05',
  'question': '聯合密度 f(x,y)=2，支撐 0<y<x<1。邊際密度 f_X(x) 是多少？',
  'answer': 'f_X(x)=2x，0<x<1。',
  'explanation': '固定 x 後 y∈(0,x)，所以 ∫₀ˣ2dy=2x。'},
 {'id': 'ch05-q02',
  'chapterId': 'ch05',
  'question': '同一模型下 f_{Y|X}(y|x) 是多少？',
  'answer': '1/x，0<y<x。',
  'explanation': 'f_{Y|X}=f(x,y)/f_X(x)=2/(2x)=1/x。'},
 {'id': 'ch05-q03',
  'chapterId': 'ch05',
  'question': '同一聯合密度在支撐集上的總積分是多少？',
  'answer': '1。',
  'explanation': '∫₀¹∫₀ˣ2dy dx=∫₀¹2x dx=1。'},
 {'id': 'ch05-q04',
  'chapterId': 'ch05',
  'question': '求 f_X(x) 時，應把 y 設為 0 還是對 y 積分？',
  'answer': '對 y 積分。',
  'explanation': '邊際化是把不關心的變數加總或積分掉。'},
 {'id': 'ch05-q05',
  'chapterId': 'ch05',
  'question': '若 f_{X,Y}(x,y)=f_X(x)f_Y(y) 在整個支撐上成立，且支撐相容，代表什麼？',
  'answer': 'X 與 Y 獨立。',
  'explanation': '聯合分配因子分解為邊際乘積是獨立性的等價表示。'},
 {'id': 'ch06-q01',
  'chapterId': 'ch06',
  'question': 'Var(X)=4、Var(Y)=9、Cov(X,Y)=3，Var(X+Y) 是多少？',
  'answer': '19。',
  'explanation': '4+9+2×3=19。'},
 {'id': 'ch06-q02',
  'chapterId': 'ch06',
  'question': 'E(Y|X)=2X 且 E(X)=1，E(Y) 是多少？',
  'answer': '2。',
  'explanation': '反覆期望：E(Y)=E[E(Y|X)]=E(2X)=2。'},
 {'id': 'ch06-q03',
  'chapterId': 'ch06',
  'question': '若 Cov(X,Y)=0，是否一般可推出 X、Y 獨立？',
  'answer': '不可以。',
  'explanation': '零共變異數只排除線性共同變動；一般非線性依賴仍可能存在。'},
 {'id': 'ch06-q04',
  'chapterId': 'ch06',
  'question': 'E(aX+bY) 是否需要 X、Y 獨立才能等於 aE(X)+bE(Y)？',
  'answer': '不需要。',
  'explanation': '期望的線性性不要求獨立。'},
 {'id': 'ch06-q05',
  'chapterId': 'ch06',
  'question': '全變異公式把 Var(Y) 拆成哪兩部分？',
  'answer': 'E[Var(Y|X)] 與 Var(E[Y|X])。',
  'explanation': '前者是平均條件內變異，後者是條件平均之間的變異。'},
 {'id': 'ch07-q01',
  'chapterId': 'ch07',
  'question': '二維常態中 Var(X)=Var(Y)=1、Cov(X,Y)=0.5，Var(X+Y) 是多少？',
  'answer': '3。',
  'explanation': '1+1+2×0.5=3。'},
 {'id': 'ch07-q02',
  'chapterId': 'ch07',
  'question': '同一模型下 Var(Y|X=x) 是多少？',
  'answer': '0.75。',
  'explanation': '1-(0.5²/1)=0.75。'},
 {'id': 'ch07-q03',
  'chapterId': 'ch07',
  'question': '同一模型且兩均值為 0 時，E(Y|X=x) 是多少？',
  'answer': '0.5x。',
  'explanation': '條件平均為 Cov(X,Y)/Var(X)×x=0.5x。'},
 {'id': 'ch07-q04',
  'chapterId': 'ch07',
  'question': '聯合多元常態下 Cov(X,Y)=0 可推出什麼？',
  'answer': 'X 與 Y 獨立。',
  'explanation': '這是聯合常態的特殊性；一般分配不成立。'},
 {'id': 'ch07-q05',
  'chapterId': 'ch07',
  'question': '只有 X、Y 各自邊際常態，能否保證 (X,Y) 聯合常態？',
  'answer': '不能。',
  'explanation': '邊際常態不足以決定聯合分配。'},
 {'id': 'ch08-q01',
  'chapterId': 'ch08',
  'question': 'X~Uniform(-1,1)、Y=X²，f_Y(y) 為多少（0<y<1）？',
  'answer': '1/(2√y)。',
  'explanation': '±√y 兩個逆像各貢獻 (1/2)×1/(2√y)，相加得 1/(2√y)。'},
 {'id': 'ch08-q02',
  'chapterId': 'ch08',
  'question': 'U=X+Y、V=X-Y，逆轉換 (u,v)→(x,y) 的 Jacobian 絕對值是多少？',
  'answer': '1/2。',
  'explanation': 'x=(u+v)/2、y=(u-v)/2，其 2×2 Jacobian 行列式為 -1/2，取絕對值得 1/2。'},
 {'id': 'ch08-q03',
  'chapterId': 'ch08',
  'question': '密度變數轉換公式中的 Jacobian 行列式為何取絕對值？',
  'answer': '因為密度需要的是局部體積縮放量，方向翻轉不應產生負機率。',
  'explanation': '行列式符號描述定向，機率體積只看大小。'},
 {'id': 'ch08-q04',
  'chapterId': 'ch08',
  'question': '多對一轉換時只取一個逆像是否足夠？',
  'answer': '不夠。',
  'explanation': '必須把所有落在原支撐內的逆像密度貢獻相加。'},
 {'id': 'ch08-q05',
  'chapterId': 'ch08',
  'question': '完成轉換後是否仍可直接沿用原支撐集？',
  'answer': '不可以。',
  'explanation': '新變數有自己的支撐，必須一起轉換。'},
 {'id': 'ch09-q01',
  'chapterId': 'ch09',
  'question': 'X~Poisson(λ) 的 MGF 是什麼？',
  'answer': 'exp{λ(e^t-1)}。',
  'explanation': '由 E(e^{tX}) 加總 Poisson PMF 可得。'},
 {'id': 'ch09-q02',
  'chapterId': 'ch09',
  'question': 'Poisson(λ) 的 MGF 一階導數在 t=0 等於什麼？',
  'answer': 'λ。',
  'explanation': 'M′(0)=E(X)=λ。'},
 {'id': 'ch09-q03',
  'chapterId': 'ch09',
  'question': '獨立 Poisson(2) 與 Poisson(3) 相加服從什麼分配？',
  'answer': 'Poisson(5)。',
  'explanation': '獨立和的 MGF 相乘後仍是 Poisson 形式，參數相加。'},
 {'id': 'ch09-q04',
  'chapterId': 'ch09',
  'question': 'MGF 是否對每個分配都必定在 0 附近有限存在？',
  'answer': '不是。',
  'explanation': '有些重尾分配沒有 0 鄰域上的有限 MGF。'},
 {'id': 'ch09-q05',
  'chapterId': 'ch09',
  'question': '特徵函數是否對每個機率分配存在？',
  'answer': '是。',
  'explanation': '|e^{itX}|=1，使期望總有定義。'}]
