from __future__ import annotations

QUESTIONS_B = [{'id': 'ch10-q01',
  'chapterId': 'ch10',
  'question': 'n=4 的 iid Uniform(0,1) 樣本，最大值期望是多少？',
  'answer': '4/5。',
  'explanation': 'E(X_(n))=n/(n+1)=4/5。'},
 {'id': 'ch10-q02',
  'chapterId': 'ch10',
  'question': '同一樣本最小值期望是多少？',
  'answer': '1/5。',
  'explanation': 'E(X_(1))=1/(n+1)=1/5。'},
 {'id': 'ch10-q03',
  'chapterId': 'ch10',
  'question': 'iid 樣本最大值 M 的 CDF 如何由母體 CDF F 表示？',
  'answer': 'F_M(x)=[F(x)]^n。',
  'explanation': 'M≤x 等價於全部 Xi≤x；iid 下機率相乘。'},
 {'id': 'ch10-q04',
  'chapterId': 'ch10',
  'question': 'X_(1) 表示第一筆抽到的觀測值嗎？',
  'answer': '不是。',
  'explanation': 'X_(1) 是排序後的最小值。'},
 {'id': 'ch10-q05',
  'chapterId': 'ch10',
  'question': 'Uniform(0,1) 的第 k 個次序統計量可辨認為哪類分配？',
  'answer': 'Beta(k,n+1-k)。',
  'explanation': '其密度與 Beta(k,n+1-k) 形式相同。'},
 {'id': 'ch11-q01',
  'chapterId': 'ch11',
  'question': '母體 σ=4、n=64 時，X̄ 的標準誤是多少？',
  'answer': '0.5。',
  'explanation': 'SE=σ/√n=4/8=0.5。'},
 {'id': 'ch11-q02',
  'chapterId': 'ch11',
  'question': '同例 μ=10，P(|X̄-10|≤1) 用 CLT 近似約多少？',
  'answer': '約 0.9545。',
  'explanation': '標準化界線為 ±2，P(|Z|≤2)≈0.9545。'},
 {'id': 'ch11-q03',
  'chapterId': 'ch11',
  'question': 'LLN 主要描述樣本平均的哪一件事？',
  'answer': '在條件下收斂到母體平均。',
  'explanation': 'LLN 說穩定位置，不直接提供標準化後的極限形狀。'},
 {'id': 'ch11-q04',
  'chapterId': 'ch11',
  'question': 'CLT 是否表示原始資料 Xi 本身會隨 n 增大變成常態？',
  'answer': '不是。',
  'explanation': 'CLT 描述適當標準化的和或平均數之抽樣分布。'},
 {'id': 'ch11-q05',
  'chapterId': 'ch11',
  'question': '若 √n(X̄-2)⇒N(0,9)，對 g(x)=log x 用 Delta method，漸近變異數是多少？',
  'answer': '9/4。',
  'explanation': 'g′(2)=1/2，所以新變異數=(1/2)²×9=9/4。'},
 {'id': 'ch12-q01',
  'chapterId': 'ch12',
  'question': 'n=10、S²=4、假設 σ²=4，(n-1)S²/σ² 是多少？',
  'answer': '9。',
  'explanation': '9×4/4=9。'},
 {'id': 'ch12-q02',
  'chapterId': 'ch12',
  'question': 'n=16、X̄=12、μ₀=10、S=4，一樣本 t 統計量是多少？',
  'answer': '2。',
  'explanation': 'S/√n=4/4=1，所以 t=(12-10)/1=2。'},
 {'id': 'ch12-q03',
  'chapterId': 'ch12',
  'question': '上一題 t 統計量的自由度是多少？',
  'answer': '15。',
  'explanation': '一樣本 t 使用 n-1=15。'},
 {'id': 'ch12-q04',
  'chapterId': 'ch12',
  'question': '常態樣本下 X̄ 與 S² 是否獨立？',
  'answer': '是。',
  'explanation': '這是常態母體特有的重要有限樣本結果。'},
 {'id': 'ch12-q05',
  'chapterId': 'ch12',
  'question': '一樣本 t 的精確有限樣本分布是否對任意母體都成立？',
  'answer': '不是。',
  'explanation': '標準精確 t 結果依賴 iid 常態母體；非正態時通常只能談近似或穩健性。'},
 {'id': 'ch13-q01',
  'chapterId': 'ch13',
  'question': 'Exponential(rate=λ) iid 樣本的 λ MLE 是什麼？',
  'answer': '1/X̄。',
  'explanation': 'score n/λ-Σx_i=0，故 λ̂=n/Σx_i=1/X̄。'},
 {'id': 'ch13-q02',
  'chapterId': 'ch13',
  'question': '樣本 2、1、3 來自 Exponential(rate=λ)，λ̂_MLE 是多少？',
  'answer': '0.5。',
  'explanation': 'X̄=2，所以 λ̂=1/2=0.5。'},
 {'id': 'ch13-q03',
  'chapterId': 'ch13',
  'question': 'Bernoulli(p) iid 樣本的 p MLE 是什麼？',
  'answer': 'X̄。',
  'explanation': '最大化 p^{Σx}(1-p)^{n-Σx} 得 p̂=Σx/n。'},
 {'id': 'ch13-q04',
  'chapterId': 'ch13',
  'question': 'Uniform(0,θ) iid 樣本的 θ MLE 是什麼？',
  'answer': '樣本最大值 X_(n)。',
  'explanation': 'θ 必須至少等於最大觀測，likelihood 在可行區內隨 θ 增大而下降，因此取最小可行 θ=X_(n)。'},
 {'id': 'ch13-q05',
  'chapterId': 'ch13',
  'question': 'likelihood L(θ;x) 在古典推論中是否是 θ 的機率密度？',
  'answer': '不是。',
  'explanation': '資料 x 固定後，L 只是 θ 的函數，未必對 θ 積分為 1。'},
 {'id': 'ch14-q01',
  'chapterId': 'ch14',
  'question': 'Bernoulli(p) iid 樣本對 p 的自然充分統計量是什麼？',
  'answer': 'T=ΣX_i。',
  'explanation': 'likelihood 對資料的 p 依賴只透過成功總數。'},
 {'id': 'ch14-q02',
  'chapterId': 'ch14',
  'question': '充分統計量是否自動是無偏估計量？',
  'answer': '不是。',
  'explanation': '充分性描述資訊保存，與估計偏誤是不同性質。'},
 {'id': 'ch14-q03',
  'chapterId': 'ch14',
  'question': 'Neyman–Fisher 因子分解定理的核心形式是什麼？',
  'answer': 'f(x;θ)=g(T(x),θ)h(x)。',
  'explanation': '資料與 θ 的共同依賴只經 T(x) 進入。'},
 {'id': 'ch14-q04',
  'chapterId': 'ch14',
  'question': '完備性比充分性更強還是兩者同義？',
  'answer': '不是同義；完備性是另一個更強的函數期望唯一性性質。',
  'explanation': '充分性不會自動推出完備性。'},
 {'id': 'ch14-q05',
  'chapterId': 'ch14',
  'question': 'Lehmann–Scheffé 定理要取得唯一 UMVU，通常需要哪種統計量？',
  'answer': '完備且充分的統計量。',
  'explanation': '將無偏估計量表示為 complete sufficient statistic 的函數可得到唯一 UMVU。'},
 {'id': 'ch15-q01',
  'chapterId': 'ch15',
  'question': 'Bernoulli(p) 樣本平均 p̂ 的 Var(p̂) 是多少？',
  'answer': 'p(1-p)/n。',
  'explanation': '獨立 Bernoulli 平均的變異數為 p(1-p)/n。'},
 {'id': 'ch15-q02',
  'chapterId': 'ch15',
  'question': 'Bernoulli(p) n 筆樣本的 Fisher information I_n(p) 是多少？',
  'answer': 'n/[p(1-p)]。',
  'explanation': '單筆 information 為 1/[p(1-p)]，iid 相加得 n 倍。'},
 {'id': 'ch15-q03',
  'chapterId': 'ch15',
  'question': '相應 CRLB 1/I_n(p) 是多少？',
  'answer': 'p(1-p)/n。',
  'explanation': '取 Fisher information 倒數即可，且樣本平均達到此界。'},
 {'id': 'ch15-q04',
  'chapterId': 'ch15',
  'question': 'MSE 與 bias、variance 的關係？',
  'answer': 'MSE=Variance+Bias²。',
  'explanation': '平方誤差期望可分解為變異數與偏誤平方。'},
 {'id': 'ch15-q05',
  'chapterId': 'ch15',
  'question': 'Rao–Blackwell 化後變異數是否一定嚴格變小？',
  'answer': '不一定；只保證不增加。',
  'explanation': '若原估計量已是充分統計量的函數等情況，可保持相同。'},
 {'id': 'ch16-q01',
  'chapterId': 'ch16',
  'question': 'σ=2、n=100、X̄=10，95% z 信賴區間是多少？',
  'answer': '[9.608, 10.392]。',
  'explanation': 'SE=0.2，誤差界 1.96×0.2=0.392。'},
 {'id': 'ch16-q02',
  'chapterId': 'ch16',
  'question': 'n=25、X̄=20、S=5，取 t_{24,0.975}=2.064，95% t 區間是多少？',
  'answer': '[17.936, 22.064]。',
  'explanation': 'S/√n=1，故 20±2.064。'},
 {'id': 'ch16-q03',
  'chapterId': 'ch16',
  'question': '古典 95% CI 算出後，可否說固定參數 θ 有 95% 機率落在該已固定區間？',
  'answer': '不可以。',
  'explanation': '95% 指重複抽樣程序的覆蓋率；觀察後 θ 在古典架構中仍是固定量。'},
 {'id': 'ch16-q04',
  'chapterId': 'ch16',
  'question': 'σ 未知且小樣本常態母體的平均數區間通常用 z 還是 t？',
  'answer': 't。',
  'explanation': '以 S 估 σ 後，精確樞紐量服從 t_{n-1}。'},
 {'id': 'ch16-q05',
  'chapterId': 'ch16',
  'question': '樞紐量的關鍵特徵是什麼？',
  'answer': '其抽樣分布不含未知參數。',
  'explanation': '因此可以把固定機率敘述反解成參數信賴區間。'},
 {'id': 'ch17-q01',
  'chapterId': 'ch17',
  'question': 'H0:μ=10，σ=2，n=100，X̄=10.5，z 統計量是多少？',
  'answer': '2.5。',
  'explanation': '(10.5-10)/(2/10)=0.5/0.2=2.5。'},
 {'id': 'ch17-q02',
  'chapterId': 'ch17',
  'question': '上一題雙尾 p-value 約多少？',
  'answer': '約 0.0124。',
  'explanation': '2[1-Φ(2.5)]≈0.0124。'},
 {'id': 'ch17-q03',
  'chapterId': 'ch17',
  'question': 'p-value 能否解讀為 H0 為真的機率？',
  'answer': '不能。',
  'explanation': 'p-value 是在 H0 模型下觀察到同等或更極端資料的尾端機率。'},
 {'id': 'ch17-q04',
  'chapterId': 'ch17',
  'question': 'power function π(θ) 表示什麼？',
  'answer': '參數為 θ 時拒絕 H0 的機率。',
  'explanation': 'π(θ)=Pθ(拒絕 H0)。'},
 {'id': 'ch17-q05',
  'chapterId': 'ch17',
  'question': 'Neyman–Pearson 引理最直接處理哪種問題？',
  'answer': 'simple H0 對 simple H1。',
  'explanation': '兩邊都完全指定分配時，likelihood-ratio 形式給定 level 下最強力檢定。'},
 {'id': 'ch18-q01',
  'chapterId': 'ch18',
  'question': 'UMP 檢定是否對每個複合對立假設都一定存在？',
  'answer': '不一定。',
  'explanation': 'UMP 要同時對 H1 每個參數值最強，很多雙尾或多參數問題不存在。'},
 {'id': 'ch18-q02',
  'chapterId': 'ch18',
  'question': 'LRT 的 Λ=sup_{Θ0}L/sup_{Θ}L 越小，通常越支持拒絕哪個假設？',
  'answer': '拒絕 H0。',
  'explanation': '受限模型的最佳 likelihood 相對完整模型越差，越不利 H0。'},
 {'id': 'ch18-q03',
  'chapterId': 'ch18',
  'question': 'Wilks 定理下 -2logΛ 的 χ² 分布是有限樣本精確結果還是漸近結果？',
  'answer': '漸近結果。',
  'explanation': '需正則條件且樣本量大；特殊模型才另有精確有限樣本校準。'},
 {'id': 'ch18-q04',
  'chapterId': 'ch18',
  'question': 'Wilks χ² 的自由度通常對應什麼？',
  'answer': '完整模型與 H0 受限模型的自由參數維度差。',
  'explanation': '在正則巢狀模型中，限制數即常見自由度。'},
 {'id': 'ch18-q05',
  'chapterId': 'ch18',
  'question': 'N(μ,σ²)、σ 已知的 H0:μ=μ0 雙尾 LRT 與哪個熟悉檢定等價？',
  'answer': '雙尾 z 檢定。',
  'explanation': 'LRT 最終依 |X̄-μ0| 拒絕，與 z 的雙尾拒絕域相同。'},
 {'id': 'ch19-q01',
  'chapterId': 'ch19',
  'question': 'x=(1,2,3)、y=(2,4,5) 的簡單 OLS 斜率是多少？',
  'answer': '1.5。',
  'explanation': 'Sxy=3、Sxx=2，所以 b1=3/2=1.5。'},
 {'id': 'ch19-q02',
  'chapterId': 'ch19',
  'question': '同一資料的 OLS 截距是多少？',
  'answer': '2/3。',
  'explanation': 'b0=ȳ-b1x̄=11/3-1.5×2=2/3。'},
 {'id': 'ch19-q03',
  'chapterId': 'ch19',
  'question': '同一資料的 R² 是多少？',
  'answer': '27/28，約 0.9643。',
  'explanation': 'SSE=1/6、SST=14/3，所以 1-(1/6)/(14/3)=27/28。'},
 {'id': 'ch19-q04',
  'chapterId': 'ch19',
  'question': 'Gauss–Markov 定理的 BLUE 結論是否需要常態誤差？',
  'answer': '不需要。',
  'explanation': '常態性不是 BLUE 的必要條件；它主要用於傳統有限樣本 t/F 精確推論。'},
 {'id': 'ch19-q05',
  'chapterId': 'ch19',
  'question': 'XᵀX 不可逆時，可否直接使用 (XᵀX)^{-1}Xᵀy？',
  'answer': '不可以。',
  'explanation': '此閉式解要求設計矩陣 X 具有滿 column rank，使 XᵀX 可逆。'}]
