from __future__ import annotations

CHAPTERS_B = [{'id': 'ch10',
  'slug': 'order-statistics',
  'title': '次序統計量與樣本極值',
  'problem': '把樣本由小到大排序後，最小值、最大值與中位數的分配如何推導？',
  'intuition': ['次序統計量不是新的觀測值，而是同一組 iid 樣本排序後的位置。最大值事件 X_(n)≤x 等價於每個 Xi≤x，因此 CDF 很容易由獨立性推得 F(x)^n。',
                '最小值、最大值與中位數常用來研究極值、分位數與非參數方法。本章聚焦常見精確分配，不擴張到完整極值理論。'],
  'definitions': [('次序統計量（order statistic）', 'X_(1)≤…≤X_(n) 為樣本排序後的值。'),
                  ('樣本最大值', 'X_(n)，其 CDF 在 iid 情況為 F(x)^n。'),
                  ('樣本最小值', 'X_(1)，其存活機率 P(X_(1)>x)=[1-F(x)]^n。')],
  'formulas': [('F_{X_{(n)}}(x)=[F(x)]^n', 'iid 樣本最大值的 CDF。'),
               ('f_{X_{(k)}}(x)=\\frac{n!}{(k-1)!(n-k)!}[F(x)]^{k-1}[1-F(x)]^{n-k}f(x)', '連續 iid 樣本第 k 個次序統計量的密度。')],
  'example': ['例：X₁,…,X_n iid~Uniform(0,1)。最大值 M 的 CDF 為 P(M≤m)=m^n，0<m<1。',
              '因此 f_M(m)=nm^{n-1}，而 E(M)=n/(n+1)。同理 E(X_(1))=1/(n+1)。',
              'n=4 時，樣本最大值期望為 4/5，最小值期望為 1/5。'],
  'traps': ['把 X_(1) 當成第一筆抽到的觀測。', '最大值 CDF 寫成 1-F(x)^n。', '次序統計量公式忘記 iid 與連續型條件。'],
  'exam': ['極值先從事件等價關係推 CDF。', '中間次序統計量再用通用密度式。', 'Uniform 樣本可用 Beta 分配辨認次序統計量。'],
  'checks': ['U(0,1) 樣本 n=4 的最大值期望？', '同樣本最小值期望？', 'iid 樣本最大值的 CDF 如何寫？'],
  'figure': ('排序後的樣本', ['最小值', '中間次序', '最大值', '分位數'])},
 {'id': 'ch11',
  'slug': 'limit-theorems',
  'title': '隨機收斂、LLN、CLT、Slutsky 與 Delta method',
  'problem': '樣本很大時，為什麼平均數會穩定、又為什麼許多統計量近似常態？',
  'intuition': ['大數法則（LLN）處理「收斂到哪裡」：樣本平均在條件下靠近母體平均。中央極限定理（CLT）處理「以多快、用什麼形狀波動」：適當標準化後近似常態。',
                'Slutsky 定理讓收斂中的隨機量可被一致估計量替代；Delta method 則把常態近似穿過平滑函數。這些是大樣本推論的骨架。'],
  'definitions': [('依機率收斂（convergence in probability）', '對任意 ε>0，P(|X_n-X|>ε)→0。'),
                  ('分布收斂（convergence in distribution）', 'CDF 在極限分布連續點收斂。'),
                  ('中央極限定理（CLT）', '在典型 iid、有限變異數條件下，標準化樣本平均分布收斂到 N(0,1)。')],
  'formulas': [('\\sqrt{n}\\frac{\\bar X-\\mu}{\\sigma}\\Rightarrow N(0,1)', 'iid、E(X)=μ、0<Var(X)=σ²<∞ 的經典 CLT。'),
               ('\\sqrt n\\{g(\\hat\\theta)-g(\\theta)\\}\\Rightarrow N(0,[g^\\prime(\\theta)]^2V)',
                '若 √n(θ̂-θ)⇒N(0,V) 且 g 在 θ 可微，為一維 Delta method。')],
  'example': ['例：母體平均 10、標準差 4，n=64。X̄ 的標準誤為 4/8=0.5。',
              'CLT 下 P(|X̄-10|≤1)≈P(|Z|≤2)≈0.9545。',
              '若 √n(X̄-2)⇒N(0,9)，取 g(x)=log x，g′(2)=1/2，則 √n(log X̄-log2) 的漸近變異數為 9/4。'],
  'traps': ['把 LLN 說成樣本平均在有限 n 必然等於 μ。', '把 CLT 說成原始資料一定近似常態。', 'Delta method 忘記函數在目標點需可微且導數可能為 0。'],
  'exam': ['先分清 LLN 問穩定、CLT 問抽樣分布。', '標準化一定檢查 √n 與 σ。', '函數統計量先找導數再套 Delta method。'],
  'checks': ['例中 n=64 時 X̄ 的 SE？', 'P(|X̄-10|≤1) 的 CLT 近似約多少？', 'Delta method 的核心數學工具是什麼？'],
  'figure': ('大樣本推論骨架', ['LLN', 'CLT', 'Slutsky', 'Delta method'])},
 {'id': 'ch12',
  'slug': 'sampling-distributions',
  'title': '抽樣分配：Chi-square、t 與 F',
  'problem': '常態母體下，樣本平均與樣本變異數為什麼會導出 χ²、t、F 分配？',
  'intuition': ['推論公式不是憑空出現。若樣本來自常態母體，X̄ 與 S² 有特殊的獨立結構；標準化平均數是常態，標準化樣本變異數是 χ²，兩者組合形成 t，再由兩個獨立 χ² 比值形成 F。',
                '這些是「精確有限樣本」結果，條件比 CLT 的大樣本近似更強。考試最常見錯誤就是看到 t、χ²、F 卻忘了常態與獨立條件。'],
  'definitions': [('卡方分配（chi-square）', '獨立標準常態平方和；自由度決定形狀。'),
                  ('Student t 分配', '標準常態除以獨立 χ²/df 的平方根。'),
                  ('F 分配', '兩個獨立 χ²/df 的比值。')],
  'formulas': [('\\frac{(n-1)S^2}{\\sigma^2}\\sim\\chi^2_{n-1}', 'Xi iid~N(μ,σ²) 時的精確結果。'),
               ('\\frac{\\bar X-\\mu}{S/\\sqrt n}\\sim t_{n-1}', '常態母體、σ 未知時的一樣本 t 樞紐量。')],
  'example': ['例：n=10、樣本變異數 S²=4，若假設母體變異數 σ²=4，則 χ² 統計量=(9×4)/4=9。',
              '若 n=16、X̄=12、μ₀=10、S=4，則 t=(12-10)/(4/4)=2，自由度 15。',
              '兩個獨立常態樣本的變異數比在適當標準化後可形成 F；若只拿相關樣本變異數相除，不能直接套 F。'],
  'traps': ['把 S² 的分母 n 與 n-1 混用。', 't 分配在任意小樣本母體都精確成立。', 'F 比值忘記兩個 χ² 來源需獨立。'],
  'exam': ['先問是精確常態理論還是大樣本近似。', 'χ² 變異數題先確認 S² 定義。', 't 題自由度與估計掉的平均數參數連在一起。'],
  'checks': ['例中 χ² 統計量是多少？', '例中 t 統計量是多少？', '一樣本 t 精確分配的核心母體條件是什麼？'],
  'figure': ('抽樣分配家族', ['Normal', 'Chi-square', 't', 'F'])},
 {'id': 'ch13',
  'slug': 'point-estimation',
  'title': '點估計：動差法與最大概似',
  'problem': '如何從樣本建立未知參數的估計量？動差法與 MLE 各在做什麼？',
  'intuition': ['動差法（MOM）把樣本動差對上理論動差；最大概似估計（MLE）則把觀察到的樣本視為固定，選最能讓這組資料出現的參數值。',
                'Likelihood 不是參數的機率分布；參數在古典推論裡是固定未知量。最大化 log-likelihood 通常較方便，但還要檢查參數空間、邊界與二階條件。'],
  'definitions': [('概似函數（likelihood）', 'L(θ;x)=f(x;θ) 視為 θ 的函數；x 已觀察固定。'),
                  ('動差估計（MOM）', '令前幾個樣本動差等於模型對應母體動差來解參數。'),
                  ('最大概似估計（MLE）', '使 L(θ;x) 最大的參數值或參數集合。')],
  'formulas': [('L(\\theta;x_1,\\ldots,x_n)=\\prod_{i=1}^n f(x_i;\\theta)', 'iid 樣本的概似。'),
               ('\\ell(\\theta)=\\log L(\\theta)', '對數為單調函數，最大化 L 與最大化 log L 的解相同。')],
  'example': ['例：X_i iid~Exponential(rate=λ)，ℓ(λ)=n logλ-λΣx_i。',
              '微分令 0：n/λ-Σx_i=0，所以 λ̂_MLE=n/Σx_i=1/X̄。',
              '樣本 2、1、3 時 X̄=2，因此 λ̂=0.5。若模型是 Uniform(0,θ)，MLE 反而落在樣本最大值邊界，不能只靠設導數為 0。'],
  'traps': ['把 likelihood 正規化成參數的機率密度。', '只解 score=0，不檢查邊界。', '最大化 L 與最小化 -log L 的方向寫反。'],
  'exam': ['先寫支撐是否依賴參數。', 'iid 時先取 log 把乘積變加總。', '解完臨界點後檢查參數空間與邊界。'],
  'checks': ['Exponential(rate=λ) 的 MLE？', '樣本 2、1、3 時 λ̂ 是多少？', 'Uniform(0,θ) 的 θ MLE 與哪個次序統計量有關？'],
  'figure': ('估計量的建立', ['模型', '概似/動差', '最佳化', '估計值'])},
 {'id': 'ch14',
  'slug': 'sufficiency-exponential',
  'title': '充分統計量、因子分解與指數族',
  'problem': '資料中哪些部分保留了關於參數的全部樣本資訊？',
  'intuition': ['充分性是在問「知道 T(X) 之後，原始樣本還有沒有額外關於 θ 的資訊」。因子分解定理讓這個概念能直接從 likelihood 辨認。',
                '指數族把許多常見分配寫成共同形式，常自然產生低維充分統計量。完備性比充分性更強，兩者不能混為同一件事。'],
  'definitions': [('充分統計量（sufficient statistic）', '給定 T 後，樣本的條件分布不再依賴 θ。'),
                  ('因子分解定理（factorization theorem）', '在適當支配條件下，f(x;θ)=g(T(x),θ)h(x) 可判定 T 充分。'),
                  ('完備（complete）', '若對所有 θ 有 Eθ[g(T)]=0 即推出 g(T)=0 幾乎處處。')],
  'formulas': [('f(x;\\theta)=g(T(x),\\theta)h(x)', 'Neyman–Fisher 因子分解形式。'),
               ('f(x;\\eta)=h(x)\\exp\\{\\eta^\\top T(x)-A(\\eta)\\}', '典型自然指數族形式；實際充分性仍看模型與參數空間。')],
  'example': ['例：Bernoulli(p) iid 樣本的 likelihood 為 p^{Σx_i}(1-p)^{n-Σx_i}。',
              '資料對 p 的依賴只透過 T=ΣX_i，因此 T 對 p 充分。固定 n、p∈(0,1) 的 Bernoulli 家族中，這個 T 也具有完備性。',
              '「充分」不代表「無偏」，也不代表任何 T 的函數都很好；它描述的是資訊保存。'],
  'traps': ['把充分性解讀成樣本一定夠大。', '看到指數族就不檢查參數空間與統計量。', '充分與完備視為同義詞。'],
  'exam': ['先把 likelihood 中與 θ 有關部分聚在一起。', '尋找資料只透過哪些和、平方和等進入。', '若要用 Lehmann–Scheffé，必須再確認完備性。'],
  'checks': ['Bernoulli iid 樣本對 p 的自然充分統計量？', '充分性是否自動保證無偏？', 'Lehmann–Scheffé 還需要充分性之外的哪個性質？'],
  'figure': ('資料壓縮與資訊', ['完整樣本', '充分統計量', '因子分解', '完備性'])},
 {'id': 'ch15',
  'slug': 'estimator-quality',
  'title': '估計量品質：Bias、MSE、Fisher information 與 Rao–Blackwell',
  'problem': '兩個估計量都能估 θ 時，如何比較偏誤、變異、效率與資訊利用？',
  'intuition': ['估計量沒有只靠「看起來接近」就叫好。有限樣本可看 bias、variance、MSE；大樣本再看一致性與漸近分布。',
                'Fisher information 衡量 likelihood 對參數的局部敏感度；Cramér–Rao 下界在正則條件下限制無偏估計量變異數。Rao–Blackwell 則透過充分統計量條件化改善估計量。'],
  'definitions': [('偏誤（bias）', 'Bias(θ̂)=Eθ(θ̂)-θ。'),
                  ('均方誤差（MSE）', 'E[(θ̂-θ)²]=Var(θ̂)+Bias(θ̂)²。'),
                  ('Fisher information', '常用 I_n(θ)=E[(∂ℓ/∂θ)²]，等價形式需正則條件。')],
  'formulas': [('MSE(\\hat\\theta)=Var(\\hat\\theta)+Bias(\\hat\\theta)^2', '偏誤與變異的共同尺度。'),
               ('Var(\\hat\\theta)\\ge \\frac{1}{I_n(\\theta)}', '一參數無偏估計量的 Cramér–Rao 下界，需相應正則條件。')],
  'example': ['例：Bernoulli(p) 樣本平均 p̂=X̄ 無偏，Var(p̂)=p(1-p)/n。',
              'Bernoulli 樣本的 Fisher information I_n(p)=n/[p(1-p)]，所以 CRLB=p(1-p)/n；樣本平均達到此下界。',
              '若 U 是某個無偏估計量、T 是充分統計量，Rao–Blackwell 化 E(U|T) 仍無偏，且變異數不會更大。'],
  'traps': ['只比較 bias，不看 variance。', 'CRLB 不檢查無偏與正則條件就套用。', 'Rao–Blackwell 說成一定嚴格降低變異數。'],
  'exam': ['先列 bias、variance、MSE。', 'CRLB 題先確認 Fisher information 定義與正則條件。', '看到充分統計量，思考條件化能否改善估計量。'],
  'checks': ['Bernoulli 樣本平均的變異數？', '其 CRLB 是多少？', 'Rao–Blackwell 後變異數一定嚴格下降嗎？'],
  'figure': ('估計量比較', ['Bias', 'Variance/MSE', 'Information', '改善/效率'])},
 {'id': 'ch16',
  'slug': 'interval-estimation',
  'title': '區間估計與樞紐量',
  'problem': '如何從抽樣分配建構具有指定覆蓋率的信賴區間？',
  'intuition': ['信賴區間在抽樣前是隨機區間；95% 的意思是重複用同一程序時，長期約 95% 的區間涵蓋固定參數。看到資料後，古典參數不是以 95% 機率落在已固定區間內。',
                '樞紐量（pivot）的分布不含未知參數，因此可把機率敘述反解成參數區間。常態平均、常態變異數與許多大樣本區間都沿這個思路。'],
  'definitions': [('樞紐量（pivotal quantity）', '由樣本與參數構成，但其抽樣分布不含未知參數。'),
                  ('覆蓋率（coverage probability）', 'Pθ(L(X)≤θ≤U(X))。'),
                  ('信賴係數', '程序設計的目標覆蓋率，例如 1-α。')],
  'formulas': [('\\bar X\\pm z_{1-\\alpha/2}\\frac{\\sigma}{\\sqrt n}', '常態母體 σ 已知，或相應大樣本近似下的雙尾平均數區間。'),
               ('\\bar X\\pm t_{n-1,1-\\alpha/2}\\frac{S}{\\sqrt n}', '常態母體 σ 未知的一樣本平均數精確 t 區間。')],
  'example': ['例：σ=2、n=100、X̄=10，95% z 區間為 10±1.96×0.2，即 [9.608,10.392]。',
              '若 σ 未知且 n=25、X̄=20、S=5，使用 t_{24,0.975}≈2.064，區間為 20±2.064×1=[17.936,22.064]。',
              '兩個區間的差別不只臨界值；第二個把未知 σ 以 S 估計，精確 t 結果還依賴常態母體。'],
  'traps': ['把 95% CI 解釋成參數有 95% 後驗機率在已觀察區間。', 'σ 未知小樣本仍硬用 z。', '區間公式正確卻漏掉母體與抽樣條件。'],
  'exam': ['先找 pivot 或近似 pivot。', '再把中央機率不等式反解 θ。', '最後用一句話說明覆蓋率而非參數機率。'],
  'checks': ['例一 95% CI？', '例二 t 區間約多少？', '古典 95% CI 能否說 θ 有 95% 機率落在這個已算出的區間？'],
  'figure': ('信賴區間建構', ['抽樣分布', '樞紐量', '反解參數', '覆蓋率'])},
 {'id': 'ch17',
  'slug': 'testing-framework',
  'title': '檢定理論：Size、Power、p-value 與 Neyman–Pearson',
  'problem': '假設檢定如何從「拒不拒絕」提升到可比較的型一錯誤與檢定力設計？',
  'intuition': ['檢定規則把樣本空間分成拒絕域與不拒絕域。顯著水準控制 H0 為真時最壞或指定型一錯誤；power function 則描述不同參數值下拒絕 H0 的機率。',
                'p-value 是在 H0 模型下，依對立假設方向定義之「同等或更極端」資料的尾端機率，不是 H0 為真的機率。Neyman–Pearson 引理針對 simple H0 vs simple H1 給最強力檢定。'],
  'definitions': [('檢定大小（size）', '通常指 H0 參數集合內拒絕機率的上確界。'),
                  ('檢定力（power）', 'π(θ)=Pθ(拒絕 H0)。'),
                  ('簡單假設（simple hypothesis）', '完全指定分配參數；複合假設則含多個可能參數值。')],
  'formulas': [('\\Lambda(x)=\\frac{L(\\theta_1;x)}{L(\\theta_0;x)}', 'simple H1 對 simple H0 的 likelihood ratio；NP 最強力檢定拒絕於比值大者。'),
               ('z=\\frac{\\bar X-\\mu_0}{\\sigma/\\sqrt n}', '常態 σ 已知平均數 z 檢定統計量。')],
  'example': ['例：H0:μ=10，σ=2 已知，n=100，觀察 X̄=10.5。z=(0.5)/(0.2)=2.5。',
              '雙尾 p-value=2[1-Φ(2.5)]≈0.0124，因此在 α=0.05 下拒絕 H0。',
              '這不表示「H0 只有 1.24% 機率為真」；它是 H0 成立時尾端資料的機率。'],
  'traps': ['p-value 當 H0 的後驗機率。', '顯著水準當成觀察後犯錯機率。', 'Neyman–Pearson 引理直接套到任意複合對複合假設。'],
  'exam': ['先寫 H0/H1 與方向。', '再定統計量在 H0 下分布。', '若題目問最強力，先辨認是否 simple vs simple。'],
  'checks': ['例中 z 值？', '雙尾 p-value 約多少？', 'Neyman–Pearson 引理最直接處理哪種假設組合？'],
  'figure': ('檢定設計', ['H0/H1', '拒絕域', 'Size', 'Power'])},
 {'id': 'ch18',
  'slug': 'ump-lrt',
  'title': 'UMP 與概似比檢定',
  'problem': '當對立假設含多個參數值時，如何從 NP 引理延伸到 UMP 與 likelihood-ratio test？',
  'intuition': ['一致最強力（UMP）要求同一個 level-α 檢定對對立假設中每個參數值都至少不比其他檢定差，因此未必存在。具有 monotone likelihood ratio 的單參數指數族常能為單尾問題建立 UMP。',
                '概似比檢定（LRT）比較 H0 受限最大概似與完整參數空間最大概似。大樣本下 Wilks 定理常讓 -2logΛ 近似 χ²，但這需要正則條件，邊界或不可識別問題會破壞標準結果。'],
  'definitions': [('UMP 檢定', '在指定 level 下，對 H1 每個參數值皆具有最大 power 的檢定。'),
                  ('概似比統計量', 'Λ= sup_{θ∈Θ0}L(θ) / sup_{θ∈Θ}L(θ)，通常 0≤Λ≤1。'),
                  ('Wilks 定理', '在正則條件下，-2logΛ 的極限分布為自由度等於參數維度差的 χ²。')],
  'formulas': [('\\Lambda(x)=\\frac{\\sup_{\\theta\\in\\Theta_0}L(\\theta;x)}{\\sup_{\\theta\\in\\Theta}L(\\theta;x)}', 'Λ 小表示 H0 的受限最佳擬合相對差，因而傾向拒絕 H0。'),
               ('-2\\log\\Lambda\\Rightarrow\\chi^2_{d}', 'Wilks 大樣本結果；d 通常為完整與受限模型的自由參數維度差。')],
  'example': ['例：X_i~N(μ,σ²)，σ 已知，檢定 H0:μ=μ₀ 對 μ≠μ₀。',
              'LRT 化簡後會依 |X̄-μ₀| 大小拒絕，與熟悉的雙尾 z 檢定等價；這個特殊例可有精確常態校準。',
              '一般模型若只知道 Wilks 近似，不能把 χ² 極限分布誤寫成所有有限樣本都精確成立。'],
  'traps': ['認為每個複合 H1 都一定有 UMP。', 'LRT 的 Λ 大時反而拒絕 H0。', 'Wilks χ² 近似完全不需要正則條件。'],
  'exam': ['UMP 題先找單尾與 monotone likelihood ratio 結構。', 'LRT 先各自找受限與不受限 MLE。', '最後分清精確有限樣本分布與漸近 χ²。'],
  'checks': ['UMP 是否總存在？', 'LRT 的 Λ 越小通常越支持拒絕哪個假設？', 'Wilks χ² 結果是有限樣本精確還是漸近？'],
  'figure': ('複合假設檢定', ['受限 MLE', '完整 MLE', 'Likelihood ratio', '拒絕域'])},
 {'id': 'ch19',
  'slug': 'linear-model-theory',
  'title': '常態線性模型與迴歸推論',
  'problem': '如何把簡單迴歸、ANOVA 與 t/F 檢定放進同一個線性模型框架？',
  'intuition': ['線性模型 y=Xβ+ε 把多個係數一起整理。OLS 以最小平方殘差估 β；在滿秩、零條件平均與球形誤差變異等 Gauss–Markov 條件下，OLS 是線性無偏估計量中的 BLUE，不需要先假設常態。',
                '若再加上常態誤差，可得到傳統有限樣本 t 與 F 的精確分布。這一章用矩陣看懂共同結構，但不擴張成完整多元迴歸或計量經濟學。'],
  'definitions': [('線性模型', 'y=Xβ+ε；X 視設計而定，β 為未知係數。'),
                  ('OLS', '使 (y-Xβ)ᵀ(y-Xβ) 最小的估計量。'),
                  ('Gauss–Markov 定理', '在標準線性模型條件下，OLS 為 BLUE；常態性不是 BLUE 的必要條件。')],
  'formulas': [('\\hat\\beta=(X^\\top X)^{-1}X^\\top y', 'X 滿 column rank 時的 OLS 解。'),
               ('F=\\frac{(SSE_R-SSE_U)/q}{SSE_U/(n-p)}', '比較 q 個線性限制的常見巢狀模型 F 統計量；精確 F 校準需常態線性模型條件。')],
  'example': ['例：簡單迴歸資料 x=(1,2,3)、y=(2,4,5)。x̄=2、ȳ=11/3，Sxx=2、Sxy=3。',
              '因此斜率 b₁=Sxy/Sxx=1.5，截距 b₀=ȳ-b₁x̄=2/3。',
              '此例 SSE=1/6，SST=14/3，所以 R²=1-SSE/SST=27/28≈0.9643。R² 高仍不等於因果關係成立。'],
  'traps': ['把 Gauss–Markov 說成必須常態才成立。', 'XᵀX 不可逆時仍直接套反矩陣公式。', 'R² 高就宣稱因果或模型沒有規格問題。'],
  'exam': ['先確認 X 的維度與 rank。', '分清 BLUE 條件與精確 t/F 的常態條件。', '限制檢定用受限與不受限 SSE 比較。'],
  'checks': ['例中 OLS 斜率？', '例中截距？', 'Gauss–Markov 的 BLUE 結論是否需要常態誤差？'],
  'figure': ('線性模型統一觀', ['設計矩陣', 'OLS', '抽樣分布', 't/F 推論'])}]
