#!/usr/bin/env python3
from pathlib import Path

WORKFLOW = Path('.github/workflows/deploy-pages.yml')
text = WORKFLOW.read_text(encoding='utf-8')

old_step = '''      - name: Generate and independently validate intermediate accounting textbook
        run: |
          cp _site/data/library.json /tmp/pre-intermediate-accounting-library.json
          cat deploy/generate-intermediate-accounting.py.gz.b64.part* | tr -d '\\n' | base64 --decode > /tmp/generate-intermediate-accounting.py.gz
          echo 'b60133689f2ede497597295688b82646ba070b787ea94a78e950da5603b8bf34  /tmp/generate-intermediate-accounting.py.gz' | sha256sum --check -
          gzip --decompress --stdout /tmp/generate-intermediate-accounting.py.gz > /tmp/generate-intermediate-accounting.py
          python /tmp/generate-intermediate-accounting.py _site
          FINAL_LIBRARY_VERSION="$(python deploy/finalize_intermediate_accounting_library.py _site /tmp/pre-intermediate-accounting-library.json)"
          EXPECTED_LIBRARY_VERSION="$FINAL_LIBRARY_VERSION" PRE_LIBRARY_JSON=/tmp/pre-intermediate-accounting-library.json python deploy/validate_intermediate_accounting.py _site
          node --check _site/app.js
          node --check _site/sw.js
          echo "INTERMEDIATE_ACCOUNTING_FINAL_LIBRARY_VERSION=$FINAL_LIBRARY_VERSION"

'''

safe_step = '''      - name: Generate and independently validate intermediate accounting textbook
        run: |
          if python -c "import json; data=json.load(open('_site/data/library.json', encoding='utf-8')); raise SystemExit(0 if any(book['id']=='intermediate-accounting' for book in data['books']) else 1)"; then
            echo "Intermediate accounting already generated by canonical finalizer; validating existing output"
            FINAL_LIBRARY_VERSION="$(python -c "import json; print(json.load(open('_site/data/library.json', encoding='utf-8'))['version'])")"
            test -f /tmp/pre-intermediate-accounting-library.json
          else
            cp _site/data/library.json /tmp/pre-intermediate-accounting-library.json
            cat deploy/generate-intermediate-accounting.py.gz.b64.part* | tr -d '\\n' | base64 --decode > /tmp/generate-intermediate-accounting.py.gz
            echo 'b60133689f2ede497597295688b82646ba070b787ea94a78e950da5603b8bf34  /tmp/generate-intermediate-accounting.py.gz' | sha256sum --check -
            gzip --decompress --stdout /tmp/generate-intermediate-accounting.py.gz > /tmp/generate-intermediate-accounting.py
            python /tmp/generate-intermediate-accounting.py _site
            FINAL_LIBRARY_VERSION="$(python deploy/finalize_intermediate_accounting_library.py _site /tmp/pre-intermediate-accounting-library.json)"
          fi
          EXPECTED_LIBRARY_VERSION="$FINAL_LIBRARY_VERSION" PRE_LIBRARY_JSON=/tmp/pre-intermediate-accounting-library.json python deploy/validate_intermediate_accounting.py _site
          node --check _site/app.js
          node --check _site/sw.js
          echo "INTERMEDIATE_ACCOUNTING_FINAL_LIBRARY_VERSION=$FINAL_LIBRARY_VERSION"

'''

if old_step in text:
    text = text.replace(old_step, safe_step, 1)
elif 'Intermediate accounting already generated by canonical finalizer' not in text:
    raise AssertionError('intermediate accounting workflow step not found or unrecognized')

WORKFLOW.write_text(text, encoding='utf-8')
print(f'deduplicated {WORKFLOW}')
