from __future__ import annotations

CHAPTERS_B = [
    {
        'id': 'ch10',
        'slug': 'binary-outcomes',
        'title': '二元依變數：LPM、Logit 與 Probit',
        'problem': '當 Y 只有 0／1 時，線性機率模型、logit 與 probit 各在估什麼？係數如何轉成機率效果？',
        'intuition': [
            '若 Y 只有 0 或 1，條件平均 E(Y|X) 就等於 P(Y=1|X)。因此把二元 Y 對 X 做 OLS，得到的 Linear Probability Model（LPM）可以直接把斜率解讀成機率的「百分點」變化。',
            'LPM 很容易解讀，但有兩個結構性限制：預測值可能跑出 0 到 1 以外，而且誤差變異 p(1-p) 天生會隨 X 改變，所以異質變異穩健標準誤通常是基本配備。',
            'Logit／probit 把 Xβ 經過 S 型函數映射到 0 與 1 之間。這讓預測機率合法，但係數本身不再等於固定的百分點效果；連續變數的邊際效果會依當下 X 而變。',
        ],
        'definitions': [
            ('Binary outcome（二元依變數）', '只取 0／1 的結果，例如是否就業、是否違約。'),
            ('Linear Probability Model, LPM', '用 OLS 直接估計 E(Y|X)=P(Y=1|X) 的線性模型。'),
            ('Logit', '用 logistic CDF 將線性指標 Xβ 映射為 0 到 1 的機率模型。'),
            ('Probit', '用標準常態 CDF 將 Xβ 映射為機率模型。'),
            ('Marginal effect（邊際效果）', 'X 小幅變動時預測機率如何改變；非線性模型中通常依 X 而異。'),
        ],
        'formulas': [
            (r'P(Y=1\mid X)=\beta_0+\beta_1X', 'LPM：beta1 是 X 增加一單位時成功機率改變多少「機率單位」，乘 100 即百分點。'),
            (r'Var(u\mid X)=p(X)[1-p(X)]', '二元 Y 的 LPM 誤差在一般情況下具有異質變異。'),
            (r'\Lambda(z)=\frac{1}{1+e^{-z}},\quad P(Y=1\mid X)=\Lambda(X\beta)', 'Logit 的 logistic CDF。'),
            (r'\frac{\partial P(Y=1\mid X)}{\partial x_j}=\beta_j p(1-p)', '單純 logit 且無交互作用時，連續 x_j 的局部邊際效果；會隨 p 改變。'),
        ],
        'example': [
            'LPM 中若就業 dummy 對訓練 dummy 的係數為 0.07，代表其他條件固定下，訓練組的預測就業機率高 0.07，也就是 7 個百分點；不是「高 7%」的相對比例。',
            'Logit 中若某觀察值的線性指標 z=0，則 p=Lambda(0)=0.5。若連續變數係數 beta=0.8，該點的邊際效果為 0.8×0.5×0.5=0.20，約 20 個百分點／一單位 X。',
            '同一 beta=0.8 在 p=0.1 時邊際效果只有 0.8×0.1×0.9=0.072，因此 logit 係數不能固定當成百分點。',
        ],
        'traps': [
            'LPM 係數 0.07 寫成「機率增加 7%」，卻沒有分清百分點與相對百分比。',
            '把 logit／probit 的原始係數直接當成機率百分點效果。',
            '認為 logit 預測落在 0～1，所以因果識別自動比 LPM 好。',
        ],
        'exam': [
            '先分 LPM 還是非線性二元模型。',
            'LPM 係數直接轉百分點；logit／probit 要看 marginal effect 或指定 X 的機率差。',
            '若題目問因果，仍要回到外生性／研究設計，函數形式不會替你解決內生性。',
        ],
        'checks': [
            'LPM 係數 0.04 應解讀成幾個百分點？',
            'logit 原始 beta 是否通常等於固定的機率百分點效果？',
            '為什麼 LPM 常搭配 heteroskedasticity-robust SE？',
        ],
        'figure': ('二元依變數模型', ['0／1 結果', 'LPM', 'Logit／Probit', '機率與邊際效果']),
    },
    {
        'id': 'ch11',
        'slug': 'time-series-basics',
        'title': '時間序列基礎：趨勢、定態與隨機漫步',
        'problem': '同一個變數沿時間觀察時，為什麼不能把每一期當成彼此獨立？什麼是趨勢、定態與虛假迴歸風險？',
        'intuition': [
            '時間序列的順序有意義。今天通常和昨天較接近，經濟變數也常帶趨勢、季節性與持續性。若忽略這些結構，傳統橫斷面直覺可能失效。',
            '弱定態的核心直覺是平均、變異數與不同期距的共變動結構不隨日曆時間改變。定態不是「完全不動」，而是統計規律相對穩定。',
            '隨機漫步 y_t=y_{t-1}+epsilon_t 會把過去衝擊永久累積，變異數隨時間增加，因此不是弱定態。兩個彼此無關但都有趨勢或單位根的序列，可能跑出高 R² 與顯著 t，形成 spurious regression。',
        ],
        'definitions': [
            ('Trend（趨勢）', '變數平均水準隨時間系統性上升或下降。'),
            ('Seasonality（季節性）', '依固定日曆頻率重複的模式。'),
            ('Lag（落後值）', '同一變數過去一期或多期的值。'),
            ('Weak stationarity（弱定態）', '平均與變異數固定，協方差只依兩期距離而非日曆時間。'),
            ('Random walk（隨機漫步）', '當期等於前期加新衝擊，衝擊被永久累積的典型非定態過程。'),
        ],
        'formulas': [
            (r'y_t=\beta_0+\beta_1t+u_t', '線性決定性趨勢的簡化表示。'),
            (r'y_t=y_{t-1}+\varepsilon_t', '無漂移 random walk；差分 Delta y_t=epsilon_t 可在適當條件下較接近定態。'),
            (r'100\Delta\ln y_t\approx\%\Delta y_t', '相鄰兩期變化不大時，log difference 乘 100 近似成長率百分比。'),
        ],
        'example': [
            '若 y_0=100，random walk 的兩期衝擊依序為 +2、-1，則 y_1=102，y_2=101。第二期的 -1 並沒有把第一期 +2 的影響完全消除。',
            '若某指數從 100 增至 105，100×[ln(105)-ln(100)] 約為 4.879%，而一般百分比成長率是 5%；小幅變化時兩者接近。',
            '看到兩條都隨時間上升的序列時，不能只因迴歸 R² 高就宣稱有經濟關係；先問趨勢、單位根、差分或協整等時間序列結構。',
        ],
        'traps': [
            '把定態理解成每一期都幾乎一樣。',
            '兩條趨勢序列高 R² 就直接說有可靠經濟關係。',
            '把 log difference 的近似百分比當成任何變化幅度下都完全等於一般百分比。',
        ],
        'exam': [
            '先畫時間圖，找趨勢、季節性、突變與持續性。',
            '看到 y_{t-1} 係數接近 1 或 random walk 用語，先想到非定態與單位根風險。',
            '成長率題分一般百分比與 log difference，寫清楚近似。',
        ],
        'checks': [
            'random walk 的一次衝擊通常是暫時還是持久？',
            '弱定態要求平均與變異數隨日曆時間改變嗎？',
            '兩條互不相關的趨勢序列是否可能跑出高 R²？',
        ],
        'figure': ('時間序列先看結構', ['原始序列', '趨勢／季節', '定態檢查', '建模與推論']),
    },
    {
        'id': 'ch12',
        'slug': 'dynamic-time-series',
        'title': '動態迴歸、序列相關與 HAC 推論',
        'problem': '如果 Y 會依賴自己的過去，或誤差會連續幾期同方向，迴歸與標準誤應如何處理？',
        'intuition': [
            '動態模型把落後的 Y 或 X 放進迴歸，讓今天反映過去資訊。最簡單 AR(1) 的 rho 衡量持續性；|rho|<1 時衝擊逐期衰減，rho 越接近 1，回到長期平均越慢。',
            'serial correlation 是誤差跨期相關。若誤差今天偏高後明天也傾向偏高，傳統獨立誤差標準誤會錯估資訊量。HAC／Newey–West 類標準誤可在適當大樣本條件下同時對異質變異與有限程度序列相關提供穩健推論。',
            '但 HAC 不是所有時間序列問題的萬靈丹。若模型含落後依變數而誤差序列相關，或解釋變數與誤差存在動態內生性，OLS 本身也可能不一致；此時只換標準誤不夠。',
        ],
        'definitions': [
            ('AR(1)', '一階自我迴歸：當期 y 由前一期 y 與新衝擊決定。'),
            ('Persistence（持續性）', '衝擊對未來 y 的影響衰減速度。'),
            ('Serial correlation（序列相關）', '誤差項在不同時間之間相關。'),
            ('HAC standard error', '對 heteroskedasticity and autocorrelation consistent 的大樣本穩健標準誤。'),
            ('Forecast error（預測誤差）', '實際值與預測值之差。'),
        ],
        'formulas': [
            (r'y_t=\alpha+\rho y_{t-1}+u_t', 'AR(1) 模型；常見弱定態條件之一為 |rho|<1。'),
            (r'E(y_t)=\frac{\alpha}{1-\rho}', '|rho|<1 且其他條件適當時 AR(1) 的長期平均。'),
            (r'\hat y_{t+1|t}=\hat\alpha+\hat\rho y_t', '一步期 AR(1) 條件平均預測。'),
        ],
        'example': [
            '某 AR(1) 模型估得 alpha=2、rho=0.8，當期 y_t=10。一步期預測為 2+0.8×10=10。',
            '長期平均也是 2/(1-0.8)=10，因此目前恰好位在長期平均。若當期 y=15，下一期條件平均預測為 14，會逐步往 10 回歸。',
            '若殘差有正序列相關，不能只看 conventional SE。可以考慮 HAC 推論，但仍要先確認解釋變數與動態誤差的外生性足以支持 OLS。',
        ],
        'traps': [
            '只要用了 HAC SE 就說所有時間序列內生性都解決。',
            'rho=0.8 就解讀成每期 y 一定增加 80%。',
            '忽略 |rho|<1 的定態條件，直接使用 alpha/(1-rho) 當長期平均。',
        ],
        'exam': [
            'AR(1) 題先看 rho 的大小與是否滿足 |rho|<1。',
            '預測用條件平均公式；長期平均和一步期預測不要混。',
            '序列相關題分兩層：點估計是否仍一致？標準誤是否需要 HAC？',
        ],
        'checks': [
            'alpha=1、rho=0.5 時的長期平均是多少？',
            '正 serial correlation 主要會讓傳統標準誤面臨什麼問題？',
            'HAC SE 能否自動修正落後 Y 與序列相關誤差造成的內生性？',
        ],
        'figure': ('動態時間序列模型', ['落後資訊', 'AR 動態', '殘差相關', 'HAC／預測']),
    },
    {
        'id': 'ch13',
        'slug': 'panel-data',
        'title': '縱橫資料：Pooled OLS、FD、FE 與 RE',
        'problem': '同一個人／公司重複觀察多期時，如何利用「個體內變化」消除看不到但固定不變的差異？',
        'intuition': [
            'Panel data 最有價值的地方，是能把每個個體不隨時間改變的看不見特質 alpha_i 隔離掉。若能力、企業文化等固定特質同時和 X 有關，直接 pooled OLS 可能把它們混進 X 的效果。',
            'First Differences 用相鄰期差分消掉 alpha_i；Fixed Effects 用每個個體減去自己的時間平均消掉 alpha_i。兩者都依賴「個體內」的 X 變化，所以完全不隨時間改變的變數在個體 FE 中無法單獨估係數。',
            'Random Effects 保留個體間與個體內變化，但需要更強假設：個體效果 alpha_i 與各期解釋變數不相關。若這個條件不可信，RE 的效率優勢換來的可能是偏誤。',
        ],
        'definitions': [
            ('Panel data（縱橫資料）', '同一組個體被重複觀察多個時點。'),
            ('Pooled OLS', '把所有 person-time 觀察值堆在一起，不特別控制個體固定效果的 OLS。'),
            ('First Differences, FD', '用相鄰期差值消除時間不變個體效果。'),
            ('Fixed Effects, FE', '用 within transformation 消除時間不變個體效果。'),
            ('Random Effects, RE', '把個體效果視為複合誤差的一部分，通常要求其與解釋變數不相關。'),
        ],
        'formulas': [
            (r'y_{it}=\beta x_{it}+\alpha_i+u_{it}', '最基本個體效果 panel 模型。'),
            (r'\Delta y_{it}=\beta\Delta x_{it}+\Delta u_{it}', 'First-difference 後時間不變 alpha_i 被消除。'),
            (r'y_{it}-\bar y_i=\beta(x_{it}-\bar x_i)+(u_{it}-\bar u_i)', 'FE within transformation。'),
            (r'Cov(x_{it},\alpha_i)=0', 'RE 直覺所需的重要正交條件；實際設定常要求對全部時點 X 都成立。'),
        ],
        'example': [
            '某人兩期資料滿足 y_it=2x_it+alpha_i+u_it，且 x 從 3 變 5。若忽略誤差差分，Delta y=2×(5-3)=4。',
            '差分後 alpha_i-alpha_i=0，因此所有時間不變的個人特質都被消掉。',
            '同樣地，若性別在觀察期內完全不變，個體 FE 中性別 dummy 本身會與個體固定效果完全共線，不能另外識別其係數；但它和時間變動變數的交互作用在有足夠變化時可能仍可識別。',
        ],
        'traps': [
            '把 FE 說成可以控制所有可能遺漏變數，包括隨時間變化的 confounders。',
            '在個體 FE 模型中要求估一個完全不隨時間變動的主效果係數。',
            '認為 RE 只是 FE 的另一種寫法，不需要更強的個體效果外生假設。',
        ],
        'exam': [
            '先圈出 alpha_i 是否時間不變。',
            'FD 直接做相鄰差；FE 做去個體平均。',
            '比較 FE／RE 時把關鍵問題寫成：alpha_i 是否可合理視為與 X 不相關？',
        ],
        'checks': [
            '個體 FE 可以單獨估完全不隨時間變動的性別 dummy 主效果嗎？',
            'First Difference 為什麼能消掉 alpha_i？',
            'RE 相比 FE 需要對 alpha_i 與 X 加上什麼額外直覺假設？',
        ],
        'figure': ('Panel 的個體內識別', ['跨個體差異', '固定 alpha_i', '個體內變化', 'FD／FE']),
    },
    {
        'id': 'ch14',
        'slug': 'instrumental-variables',
        'title': '工具變數、Wald 估計量與 2SLS',
        'problem': '當 X 內生時，什麼樣的 Z 能當工具變數？為什麼「第一階段很強」仍不足以證明 IV 有效？',
        'intuition': [
            'Instrumental Variable（IV）的想法是找一個 Z，它能推動內生 X，但不直接透過其他路徑影響 Y。如此只用 X 中由 Z 所產生的外生變動來估計效果。',
            '有效 IV 至少要同時面對兩件事：relevance，Z 確實改變 X；exogeneity／exclusion，Z 與結構誤差不相關，且對 Y 的影響只經過目標 X。第一階段資料可以支持 relevance，但不能證明 exclusion。',
            '2SLS 第一階段用 Z 與其他外生控制預測 X，第二階段再用 X 的工具變數成分估 Y。weak instrument 會讓有限樣本推論非常不可靠，因此不能只看到一個顯著星號就放心。',
        ],
        'definitions': [
            ('Instrumental variable（工具變數）', '用來提供 X 外生變動的變數 Z。'),
            ('Relevance', '工具變數對內生解釋變數有足夠預測力。'),
            ('Exogeneity / exclusion restriction', '工具變數不與結構誤差相關，且不經其他排除路徑直接影響結果。'),
            ('First stage', '將內生 X 對 Z 與外生控制做迴歸。'),
            ('Two-Stage Least Squares, 2SLS', '以工具變數投影所產生的 X 變動估計結構方程的方法。'),
        ],
        'formulas': [
            (r'X_i=\pi_0+\pi_1Z_i+v_i', '最簡化 first stage；relevance 要求 pi1 不為 0 且實務上要有足夠強度。'),
            (r'Y_i=\beta_0+\beta_1X_i+u_i', '結構方程；X 內生時 OLS 一般無法識別 beta1。'),
            (r'\hat\beta_{IV}=\frac{Cov(Z,Y)}{Cov(Z,X)}', '單一工具、單一內生 X 的簡化 IV 比率；分母不能接近 0。'),
            (r'\hat\beta_{Wald}=\frac{E(Y\mid Z=1)-E(Y\mid Z=0)}{E(X\mid Z=1)-E(X\mid Z=0)}', '二元工具的 Wald estimator；因果解讀還需要相應 IV 假設。'),
        ],
        'example': [
            '某二元工具 Z 使平均 X 從 2 增至 4，因此 first-stage difference=2；同時平均 Y 從 10 增至 16，因此 reduced-form difference=6。',
            'Wald IV=6/2=3。它把 Z 對 Y 的 reduced-form 效果除以 Z 對 X 的 first-stage 效果。',
            '但 3 能否解讀為 X 的因果效果，仍取決於 Z 是否真的只透過 X 影響 Y、是否和未觀察誤差獨立，以及在 treatment-effect heterogeneity 下需要的額外 LATE 條件。',
        ],
        'traps': [
            'first-stage 顯著就宣稱工具變數有效。',
            'Z 與 Y 無條件相關就說違反 exclusion；若路徑正是經 X，相關反而是 IV 起作用的一部分。',
            'weak instrument 只用一般 t 顯著與否判斷，忽略專門診斷與有限樣本問題。',
        ],
        'exam': [
            'IV 題一定分兩欄：Relevance 與 Exogeneity／Exclusion。',
            '二元 Z 給組平均時先算 DeltaY／DeltaX 的 Wald ratio。',
            '若問 first-stage F，說它是強度診斷的一部分，不是外生性的證明，也沒有跨所有設計通用的保證門檻。',
        ],
        'checks': [
            'Z 讓 X 增加 3、讓 Y 增加 9，Wald estimator 是多少？',
            '強 first stage 能否證明 exclusion restriction？',
            'Cov(Z,X) 接近 0 時最先擔心哪一類 IV 問題？',
        ],
        'figure': ('工具變數識別', ['Z 工具', '第一階段 X', '結果 Y', '2SLS／Wald']),
    },
    {
        'id': 'ch15',
        'slug': 'randomized-experiments',
        'title': '隨機實驗、潛在結果與 ITT',
        'problem': '為什麼隨機分派能讓簡單組間平均差具有因果意義？「未完全遵從」時又該估什麼？',
        'intuition': [
            '潛在結果框架對每個單位想像兩個結果 Y(1) 與 Y(0)，但現實一次只能觀察其中一個。因果推論的根本難題就是同一個人不能同時接受與不接受處置。',
            '隨機分派讓 treatment assignment 在設計上和處置前潛在結果獨立，因此 treatment 與 control 的平均差在重複實驗下能識別平均處置效果。它不要求樣本內每一個協變數都恰好完全平衡。',
            '若受分派的人未必照做，直接比較「實際接受處置」可能重新引入選擇偏誤。Intention-to-Treat（ITT）先比較被分派到 treatment 與 control 的結果，保留隨機化的識別。',
        ],
        'definitions': [
            ('Potential outcome（潛在結果）', 'Y_i(1) 與 Y_i(0)：同一單位在處置與未處置狀態下的兩個可能結果。'),
            ('Average Treatment Effect, ATE', 'E[Y(1)-Y(0)]，母體平均因果效果。'),
            ('Random assignment（隨機分派）', '以隨機機制決定 treatment assignment，使分派與潛在結果在設計上獨立。'),
            ('Intention-to-Treat, ITT', '依原始隨機分派組別比較結果，不因實際遵從情況重分類。'),
            ('Compliance（遵從）', '受試者是否依分派實際接受指定處置。'),
        ],
        'formulas': [
            (r'ATE=E[Y(1)-Y(0)]', '平均處置效果的目標參數。'),
            (r'\hat\tau_{diff}=\bar Y_T-\bar Y_C', '完整隨機分派下最基本的差均值估計量。'),
            (r'ITT=E[Y\mid Z=1]-E[Y\mid Z=0]', 'Z 為隨機分派；不依實際接受 treatment 與否重新分組。'),
        ],
        'example': [
            '某訓練計畫隨機分派後，treatment assignment 組平均測驗分數 75，control assignment 組平均 70。',
            '差均值為 75-70=5 分；在設計與執行有效的隨機實驗中，這是 ITT，也是完全遵從時最直接的 ATE 估計。',
            '若 treatment 組有人未參加、control 組有人自行參加，把大家依「實際參加」重分組就不再保證隨機。此時仍先報 ITT；若要估接受處置者的局部效果，需額外使用 assignment 作 IV 並加入相應假設。',
        ],
        'traps': [
            '隨機分派後看到某個 baseline 變數樣本平均不完全相等，就說隨機化一定失敗。',
            '有 noncompliance 時直接依實際 treatment 重分組並保留因果解讀。',
            '把 ITT 和「實際接受處置」效果混成同一個 estimand。',
        ],
        'exam': [
            '先圈出 random assignment 變數 Z 與 actual treatment D 是否相同。',
            '完整遵從可用 treatment-control 差均值；不完整遵從先報 ITT。',
            '看到 attrition、spillover、noncompliance 時要指出設計可能面臨的額外威脅。',
        ],
        'checks': [
            'treatment 平均 82、control 平均 76，差均值是多少？',
            'ITT 是按實際接受 treatment 還是按原始 assignment 分組？',
            '隨機分派是否要求每一個 baseline 變數在這次樣本中完全相等？',
        ],
        'figure': ('隨機實驗的比較', ['隨機分派', 'Treatment', 'Control', '平均差／ITT']),
    },
    {
        'id': 'ch16',
        'slug': 'difference-in-differences',
        'title': 'Difference-in-Differences 與平行趨勢',
        'problem': '當政策只影響一組而且有政策前後資料時，如何用 DiD 扣掉共同時間變化與固定組別差異？',
        'intuition': [
            'DiD 不直接比較政策後兩組差多少，而是比較「兩組各自從政策前到政策後改變多少」，再把兩個變化相減。這樣可消除不隨時間改變的固定組別差異與兩組共同受到的時間衝擊。',
            '核心識別假設是 parallel trends：如果沒有 treatment，處置組與控制組的結果趨勢在關心期間應可比較。它是反事實假設，不能被資料完全證明。政策前 event-study 圖能提供支持或警訊，但「所有 pre-trend 係數不顯著」不是數學上的證明。',
            '標準誤要配合 treatment assignment 與序列／群聚相關結構。當政策在州、學校、公司等群組層級給予時，常需要在相應群組層級 cluster，而不是把每一筆 person-time 當獨立。',
        ],
        'definitions': [
            ('Difference-in-Differences, DiD', '用處置組與控制組前後變化的差來估政策效果。'),
            ('Parallel trends', '若沒有處置，兩組結果的時間趨勢應可比較的識別假設。'),
            ('Treatment group', '受到政策／處置影響的組別。'),
            ('Control group', '用來近似處置組未受處置反事實趨勢的比較組。'),
            ('Event study', '以相對處置時間的 lead／lag 係數呈現動態效果與處置前趨勢資訊的迴歸圖。'),
        ],
        'formulas': [
            (r'\hat\tau_{DiD}=(\bar Y_{T,post}-\bar Y_{T,pre})-(\bar Y_{C,post}-\bar Y_{C,pre})', '最基本 2×2 DiD estimator。'),
            (r'Y_{it}=\alpha+\gamma Treat_i+\lambda Post_t+\tau(Treat_i\times Post_t)+u_{it}', '2×2 線性 DiD 表示；tau 是 DiD 係數。'),
        ],
        'example': [
            '政策前 treatment 組平均 50、control 組平均 45；政策後 treatment 70、control 55。',
            'Treatment 改變 20，Control 改變 10，因此 DiD=20-10=10。',
            '政策後的橫斷面差是 70-55=15，但其中包含政策前原本就存在的 5 分差異。DiD 把固定的組間差異扣掉後得到 10。',
        ],
        'traps': [
            '只比較政策後 treatment 與 control 的水準差就叫 DiD。',
            '政策前 event-study 係數不顯著就宣稱 parallel trends 已被證明。',
            '資料很多筆就使用 observation-level iid SE，忽略 treatment 在群組層級配置。',
        ],
        'exam': [
            '先算 Treatment 的 post-pre，再算 Control 的 post-pre，最後前者減後者。',
            '任何因果結論都要寫 parallel trends。',
            '若是多期、staggered adoption，提醒傳統 two-way fixed-effects 解讀可能需要更現代的 cohort／event-time 方法；本科核心先掌握 2×2 識別。',
        ],
        'checks': [
            'Treatment 40→58、Control 35→43，DiD 是多少？',
            'parallel trends 是政策後兩組水準相同嗎？',
            '處置前係數不顯著是否足以證明 parallel trends？',
        ],
        'figure': ('DiD 反事實趨勢', ['政策前差異', '共同趨勢', '政策後觀察', 'DiD 效果']),
    },
    {
        'id': 'ch17',
        'slug': 'regression-discontinuity',
        'title': 'Regression Discontinuity Design',
        'problem': '若 treatment 由一個明確 cutoff 決定，怎麼利用門檻附近幾乎相同的個體估計局部因果效果？',
        'intuition': [
            'RDD 利用一個 running variable R 與 cutoff c。當 treatment 在 c 的兩側突然改變，而其他決定結果的因素在 c 附近平滑延續時，結果條件平均在 cutoff 的跳躍可解讀為局部 treatment effect。',
            '它的力量來自「只比較門檻附近」。因此估到的通常是 cutoff 附近的 local effect，而不是整個母體平均效果。帶寬太寬會增加模型外推，太窄則樣本少、變異大。',
            '若個體能精確操弄 running variable 以跨過門檻，門檻兩側可能不再可比較。除了畫 outcome-R 圖，也常檢查 running variable 密度與 pre-treatment covariates 在 cutoff 是否異常跳躍。',
        ],
        'definitions': [
            ('Running variable', '決定個體距離 cutoff 遠近的連續變數。'),
            ('Cutoff', '處置規則發生不連續改變的門檻 c。'),
            ('Sharp RDD', '跨過 cutoff 時 treatment probability 從 0 跳到 1 的設計。'),
            ('Fuzzy RDD', 'cutoff 只讓 treatment probability 不連續改變，而非完全決定 treatment。'),
            ('Bandwidth', '估計時納入 cutoff 兩側多寬的資料範圍。'),
        ],
        'formulas': [
            (r'D_i=1[R_i\ge c]', 'Sharp RDD 的處置規則。'),
            (r'\tau_{RDD}=\lim_{r\downarrow c}E[Y\mid R=r]-\lim_{r\uparrow c}E[Y\mid R=r]', '在相應 continuity 與無精確操弄等條件下，cutoff 處的局部處置效果。'),
            (r'\tau_{FRD}=\frac{\text{cutoff 處 }Y\text{ 的跳躍}}{\text{cutoff 處 }D\text{ 的跳躍}}', 'Fuzzy RDD 的局部 Wald ratio 直覺。'),
        ],
        'example': [
            '某補助在分數 60 以上取得。估計 cutoff 左側的局部平均結果為 62，右側為 68。',
            'Sharp RDD 的結果跳躍為 68-62=6。若在 60 附近除了補助取得外，其他決定因素皆平滑，這 6 可解讀為 cutoff 附近的局部因果效果。',
            '但不能直接說所有分數從 0 到 100 的人平均都會有 6 的效果；那是外部效度／外推的另外問題。',
        ],
        'traps': [
            'RDD 估到 cutoff 效果後直接外推整個母體。',
            '只看 cutoff 兩側平均差，完全不問 running variable 是否被操弄。',
            '用很高次全域多項式跨大範圍配適，卻把結果當成穩健的局部設計。',
        ],
        'exam': [
            '先找 R、cutoff c 與 treatment 規則。',
            '再問 outcome 在 c 的左右極限是否跳躍、其他因素是否應平滑。',
            '答案最後一定寫「cutoff 附近 local effect」，除非題目額外提供外推條件。',
        ],
        'checks': [
            'cutoff 左側預測 10、右側 13，sharp RDD 跳躍是多少？',
            'RDD 的效果一般是 local 還是全母體 ATE？',
            '若個體能精確操弄 R 跨過 cutoff，最先威脅哪個可比較性直覺？',
        ],
        'figure': ('RDD cutoff 比較', ['Running variable', 'Cutoff', '左右局部趨勢', '結果跳躍']),
    },
    {
        'id': 'ch18',
        'slug': 'prediction-model-selection',
        'title': '預測、模型選擇與樣本外評估',
        'problem': '如果目標是預測而不是解釋因果，為什麼一定要把樣本內配適和樣本外表現分開？',
        'intuition': [
            '預測的核心問題是新資料表現。模型可以把訓練樣本記得非常好，卻在未看過資料上失敗，這叫 overfitting。單看 training R² 幾乎無法防止這件事。',
            '把資料分成 training 與 test（或使用 cross-validation）是模擬未來新資料的方式。模型選擇應在訓練／驗證流程完成，最後 test set 留作較乾淨的樣本外評估；反覆偷看 test 再調模型會污染 test。',
            'RMSE 對大誤差懲罰較重，MAE 對極端誤差較不敏感。哪個較好取決於真正的決策損失；沒有一個指標在所有問題都唯一正確。',
        ],
        'definitions': [
            ('Training set', '用來估參數與學習模型的資料。'),
            ('Test set', '盡量保留到最後，用來評估樣本外預測表現的資料。'),
            ('Overfitting（過度配適）', '模型學到訓練資料中的噪音，使 training 表現很好而新資料表現差。'),
            ('RMSE', '預測誤差平方平均後開根號，對大誤差給較高懲罰。'),
            ('MAE', '預測誤差絕對值的平均。'),
        ],
        'formulas': [
            (r'RMSE=\sqrt{\frac{1}{m}\sum_{j=1}^m(y_j-\hat y_j)^2}', '在 test sample 的常見平方損失摘要。'),
            (r'MAE=\frac{1}{m}\sum_{j=1}^m|y_j-\hat y_j|', '絕對誤差平均。'),
            (r'R^2_{test}=1-\frac{\sum_{test}(y-\hat y)^2}{\sum_{test}(y-\bar y_{test})^2}', '一種樣本外 R² 定義；可能為負，表示比直接用 test mean 作基準還差。'),
        ],
        'example': [
            '三筆 test 預測誤差為 1、-2、3。RMSE=sqrt[(1+4+9)/3]=sqrt(14/3)≈2.160；MAE=(1+2+3)/3=2。',
            '若一個複雜模型 training RMSE=0.5、test RMSE=3，而簡單模型 training RMSE=1.2、test RMSE=1.8，若目標是新資料預測，後者反而更值得選。',
            '但預測更準不表示簡單模型或複雜模型中的每個 beta 都能解讀成因果效果。Prediction 與 causal estimation 是不同 estimand／loss。',
        ],
        'traps': [
            '用 training R² 選完模型後就宣稱樣本外預測最好。',
            '反覆查看 test set 並根據 test 結果調參，最後仍把同一 test 當純樣本外驗證。',
            '預測很準就說變數係數具有因果解釋。',
        ],
        'exam': [
            '看到 prediction 先把 train、validation／CV、test 的角色分開。',
            '計算 RMSE 先平方誤差平均再開根號；MAE 則取絕對值平均。',
            '最後確認題目目標是 prediction 還是 causal interpretation，避免用錯評價標準。',
        ],
        'checks': [
            '誤差 1、-2、3 的 MAE 是多少？',
            'test R² 可以小於 0 嗎？',
            '樣本外預測較準是否足以證明係數是因果效果？',
        ],
        'figure': ('樣本外預測流程', ['Training', '模型選擇', 'Test', 'RMSE／MAE']),
    },
    {
        'id': 'ch19',
        'slug': 'empirical-workflow',
        'title': '完整實證工作流程與結果解讀',
        'problem': '從一句研究問題走到一張可信的結果表，應該依什麼順序做，才能避免事後挑模型與過度解讀？',
        'intuition': [
            '好的實證不是從「先把資料丟進很多迴歸」開始，而是先寫研究問題與 estimand，再寫識別假設。等知道想估什麼、靠什麼變動識別後，才決定資料、模型與標準誤。',
            '資料清理也屬於研究設計：樣本納入排除、變數定義、缺失值、極端值與時間窗口都可能改變 estimand。事後只保留最顯著的版本會製造 specification searching／p-hacking 風險。',
            '結果報告至少要同時給效果大小、單位、標準誤或信賴區間、樣本與模型規格，並清楚區分「資料支持的結論」和「尚需額外假設的因果／外推」。可重現性則要求別人能從原始資料處理規則重新走到同一份分析。',
        ],
        'definitions': [
            ('Estimand', '研究想知道的母體量；應先於 estimator 決定。'),
            ('Specification', '一個完整模型設定，包括樣本、變數、函數形式、控制與標準誤。'),
            ('Robustness check', '在合理替代設定下檢查主要結論是否過度依賴單一任意選擇。'),
            ('Reproducibility（可重現性）', '相同資料與明確程序可重新產生分析結果。'),
            ('p-hacking / specification searching', '反覆嘗試規格並偏好報告顯著結果，造成推論失真。'),
        ],
        'formulas': [
            (r'\text{estimate}\ \pm\ c\times SE', '報告點估計時同時呈現不確定性；c 依推論方法與信賴水準決定。'),
            (r'\text{Research question}\to\text{Estimand}\to\text{Identification}\to\text{Estimator}\to\text{Inference}', '本書建議的概念順序；不是可交換的五個按鈕。'),
        ],
        'example': [
            '研究問題：「某政策是否提高就業？」先把 estimand 定義成政策對合格者在政策後一年就業機率的平均效果，而不是先跑十種模型。',
            '若識別設計是 DiD，就先指定 treatment、control、pre、post 與 parallel-trends 理由，再決定是否加入固定效果、群聚標準誤與 event-study 診斷。',
            '報告時若估計政策提高就業 0.04、cluster-robust SE=0.015，應寫「估計提高約 4 個百分點，SE 1.5 個百分點」，並附信賴區間與假設，而不是只寫 p<0.05。',
        ],
        'traps': [
            '看到資料後才不斷改 outcome、sample 與 controls，只留下最顯著的模型。',
            '只報 p-value／星號，不報係數大小、單位與不確定性。',
            '把 robustness check 當成「換很多版本直到有顯著」的工具。',
        ],
        'exam': [
            '陌生實證題依序回答：estimand → identification → estimator → SE／inference → interpretation。',
            '表格判讀要同時看係數、SE、樣本、controls、fixed effects、clustering 與單位。',
            '最後加一句外部效度／限制，尤其是 IV LATE、RDD local effect、特定樣本或特定時期。',
        ],
        'checks': [
            'Estimand 與 estimator 哪一個應先由研究問題決定？',
            '只報 p<0.05 而不報效果大小，缺少哪一類重要資訊？',
            'robustness check 的目的是否是反覆尋找顯著規格？',
        ],
        'figure': ('完整實證工作流程', ['Estimand', 'Identification', 'Estimation', 'Inference／Report']),
    },
]
